# This is a basic workflow to help you get started with Python on GitHub Actions
name: Python Application CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Allows you to run this workflow manually from the Actions tab
#workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]  # Specify Python versions you want to test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      # Lint the Python files to enforce coding style
      run: |
        pip install flake8
        # Exit with an error code if the file has linting issues
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      # Run tests with pytest
      run: |
        pip install pytest
        pytest

  # Optionally: Build and Deploy if needed
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10  # You can customize the Python version for build

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Add any build steps here if needed, for example:
    # - name: Build the package
    #   run: python setup.py sdist bdist_wheel

    # Optionally: deploy if needed (e.g., to a server or package registry)
    # You can use GitHub's deployment actions, or any custom deployment method.

